CREATE TABLE IF NOT EXISTS articles(
                           id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                           title VARCHAR2(50) NOT NULL,
                           author VARCHAR2(50) NOT NULL,
                           PRIMARY KEY(id)
);